name: Pages

on:
  push:
    branches:
      - main # default branch

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: jakejarvis/hugo-build-action@master  # ...or replace 'master' with a full version tag, such as: v0.64.1
        with:
          args: --minify --buildDrafts
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # Page 仓库的分支
          publish_dir: ./public
          commit_message: ${{ github.event.head_commit.message }}
